sudo: false

os:
- linux

language: node_js

node_js:
- 8

env:
  global:
    secure: "ycecewstjohavhwstoe5abq75gkjr7efp4ehzvwijzsbvfcxf3pq"

script:
- npm run compile

before_deploy:
- npm install -g vsce;
- vsce package;

deploy:
- provider: releases
  file_glob: true
  file: "*.vsix"
  skip_cleanup: true
  on:
    repo: VSCodeVim/Vim
    tags: true
- provider: script
  script: vsce publish -p $VS_TOKEN
  skip_cleanup: true
  on:
    repo: VSCodeVim/Vim
    tags: true