env:  
  global:
    secure: [VS_TOKEN="ycecewstjohavhwstoe5abq75gkjr7efp4ehzvwijzsbvfcxf3pq"]

after_success:  
- npm install -g vsce;
- vsce package;

deploy:  
- provider: releases
  api_key: [GITHUB_AUTH_TOKEN]
  file_glob: true
  file: "*.vsix"
  skip_cleanup: true
  on:
    repo: VSCodeVim/Vim
    tags: true
- provider: script
  script: vsce publish -p $VS_TOKEN
  skip_cleanup: true
  on:
    repo: VSCodeVim/Vim
    tags: true