language: node_js
node_js:
  - "6"
install:
  - npm install
  - npm install -g vsce
deploy:
  - provider: script
    script:
      secure: "LwfqA9ntQ9agRREW4Ri+r6igh3zZlw7LZPykV7U8r95UPTeBrYdtBfIJLjvesMhycJPydt1aXN3eYfVzT1UgaD5nWWHjD4V32lsX9nIG3S/eoKgUWxjWI9tzMki0UGf60kmGdVCXKPYpedAG8HSRTm0pc+x97VPs8ramzR+U9sVPipwz4H3U0bIwyj6dnd+0AHt8erY0rnEON9LAzLZ4YmeH3oqdFTp79e4YIVxHo33p76/0cZEv7a7vjv++eRbml3xP2M4KsYxzBODfQz0Ov15JRNg5UXZMPPj+FjwHloc3iDLdaktHGqrk+oRMydH6Zkn+7zDSaCKFXXybkerzWbHidaq2MCWHcCTutYcMAC9dwUwJ8JQ7rvOS0srEDUpr9+qekyMLmM8J+pT5pWHKplY5nF71YARkYeiRp7TL84JsHiImCEyu9+xzq5mcMD39yRbJOSBMuxpmn3vk+mxCX3t6lr4DSGs1DY49K+ug1bbsy0Xhg4QqQvxsXKuluKI/VkmRWHTVIZ5L5Yc1yYV6NrWa+WEuVpkpjE/mBsDkFonS0kkFsYNIomQRAcFBAr84jasFqXAqfiz9KTdaO+rKGXTqesUp531XvFC/bu3q5QKYUUrk8EHPGL+RkpGb0zcReLpL6t48yYIsw4Cc3nzh9P/ZfXOhNujwWTCMN302Oxo="
    skip_cleanup: true
    on:
      repo: mike7515/code-beautifier
      tags: true